package cafemanagementsystem;

import java.sql.DriverManager;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class InsertSupplierRecordJFrame extends javax.swing.JFrame {

    /**
     * Creates new form InsertSupplierRecordJFrame
     */
    int id;
    String userName = "root";
    String password = "password";

    public InsertSupplierRecordJFrame() {
        initComponents();

        try {
            Class.forName("java.sql.DriverManager");
            Connection conn = (Connection) DriverManager.getConnection(
                    "jdbc:mysql://127.0.0.1/cafe_management_system",
                    userName,
                    password
            );
            Statement stmt = (Statement) conn.createStatement();
            String query = "SELECT MAX(sup_id) FROM suppliers;";
            ResultSet resultSet = stmt.executeQuery(query);
            if (resultSet.next()) {
                id = resultSet.getInt("MAX(sup_id)") + 1;
            } else {
                id = 1;
            }
            jTextFieldSupplierId.setText(Integer.toString(id));

        } catch (ClassNotFoundException | SQLException exec) {
            JOptionPane.showMessageDialog(null, exec.getMessage());
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackground = new javax.swing.JPanel();
        jButtonClear = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jPanelInsertCustomerRecord = new javax.swing.JPanel();
        jTextFieldSupplierName = new javax.swing.JTextField();
        jLabelProduct = new javax.swing.JLabel();
        jLabelSupplierName = new javax.swing.JLabel();
        jLabelSupplierId = new javax.swing.JLabel();
        jTextFieldSupplierId = new javax.swing.JTextField();
        jLabelEmailAddress = new javax.swing.JLabel();
        jTextFieldProduct = new javax.swing.JTextField();
        jTextFieldEmailAddress = new javax.swing.JTextField();
        jLabelProduct1 = new javax.swing.JLabel();
        jTextFieldPhoneNumber = new javax.swing.JTextField();
        jLabelEmailAddress1 = new javax.swing.JLabel();
        jScrollPaneAddress = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();
        jLabelInsertSupplierRecord = new javax.swing.JLabel();
        jButtonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Insert Customer Record");
        setName("frameInsertSupplierRecord"); // NOI18N
        setResizable(false);

        jPanelBackground.setBackground(new java.awt.Color(255, 248, 220));

        jButtonClear.setBackground(new java.awt.Color(255, 255, 255));
        jButtonClear.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jButtonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-reset-24.png"))); // NOI18N
        jButtonClear.setMnemonic('C');
        jButtonClear.setText("Clear");
        jButtonClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonSave.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSave.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-save-24.png"))); // NOI18N
        jButtonSave.setMnemonic('S');
        jButtonSave.setText("Save");
        jButtonSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jPanelInsertCustomerRecord.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInsertCustomerRecord.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldSupplierName.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N

        jLabelProduct.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabelProduct.setText("Product:");

        jLabelSupplierName.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabelSupplierName.setText("Supplier Name:");

        jLabelSupplierId.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabelSupplierId.setText("Supplier id:");

        jTextFieldSupplierId.setEditable(false);
        jTextFieldSupplierId.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jTextFieldSupplierId.setFocusable(false);
        jTextFieldSupplierId.setHighlighter(null);
        jTextFieldSupplierId.setOpaque(false);

        jLabelEmailAddress.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabelEmailAddress.setText("Email Address:");

        jTextFieldProduct.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N

        jTextFieldEmailAddress.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N

        jLabelProduct1.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabelProduct1.setText("Phone Number:");

        jTextFieldPhoneNumber.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N

        jLabelEmailAddress1.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabelEmailAddress1.setText("Address:");

        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jTextAreaAddress.setRows(5);
        jScrollPaneAddress.setViewportView(jTextAreaAddress);

        javax.swing.GroupLayout jPanelInsertCustomerRecordLayout = new javax.swing.GroupLayout(jPanelInsertCustomerRecord);
        jPanelInsertCustomerRecord.setLayout(jPanelInsertCustomerRecordLayout);
        jPanelInsertCustomerRecordLayout.setHorizontalGroup(
            jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertCustomerRecordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInsertCustomerRecordLayout.createSequentialGroup()
                        .addComponent(jLabelSupplierId, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                        .addComponent(jTextFieldSupplierId, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInsertCustomerRecordLayout.createSequentialGroup()
                        .addComponent(jLabelSupplierName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertCustomerRecordLayout.createSequentialGroup()
                        .addComponent(jLabelProduct)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInsertCustomerRecordLayout.createSequentialGroup()
                        .addComponent(jLabelProduct1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertCustomerRecordLayout.createSequentialGroup()
                        .addGroup(jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEmailAddress)
                            .addComponent(jLabelEmailAddress1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldEmailAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(jScrollPaneAddress))))
                .addContainerGap())
        );

        jPanelInsertCustomerRecordLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabelEmailAddress, jLabelEmailAddress1, jLabelProduct, jLabelSupplierId, jLabelSupplierName});

        jPanelInsertCustomerRecordLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jScrollPaneAddress, jTextFieldEmailAddress, jTextFieldPhoneNumber, jTextFieldProduct, jTextFieldSupplierId, jTextFieldSupplierName});

        jPanelInsertCustomerRecordLayout.setVerticalGroup(
            jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertCustomerRecordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSupplierId)
                    .addComponent(jTextFieldSupplierId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSupplierName)
                    .addComponent(jTextFieldSupplierName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProduct)
                    .addComponent(jTextFieldProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProduct1)
                    .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmailAddress)
                    .addComponent(jTextFieldEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEmailAddress1)
                    .addComponent(jScrollPaneAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabelInsertSupplierRecord.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        jLabelInsertSupplierRecord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInsertSupplierRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-plus-+-48.png"))); // NOI18N
        jLabelInsertSupplierRecord.setText("<html> \t<b style=\"color: #6f4e37;\"> \t\t&nbsp;Insert Supplier Record \t</b> </html>");

        jButtonClose.setBackground(new java.awt.Color(255, 255, 255));
        jButtonClose.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jButtonClose.setForeground(new java.awt.Color(204, 0, 0));
        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-macos-close-24.png"))); // NOI18N
        jButtonClose.setMnemonic('L');
        jButtonClose.setText("Close");
        jButtonClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelInsertCustomerRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jButtonSave)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonClose))
                    .addComponent(jLabelInsertSupplierRecord))
                .addContainerGap())
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInsertSupplierRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelInsertCustomerRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        String supName = jTextFieldSupplierName.getText();
        String supProd = jTextFieldProduct.getText();
        String phoneNo = jTextFieldPhoneNumber.getText();
        String emailAddr = jTextFieldEmailAddress.getText();
        String address = jTextAreaAddress.getText();

        if (supName.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Customer Name Text Field Cannot Be Empty...");
        } else if (supProd.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Product Text Field Cannot Be Empty...");
        } else if (phoneNo.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Phone Number Text Field Cannot Be Empty...");
        } else if (emailAddr.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email Address Text Field Cannot Be Empty...");
        } else if (address.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Address Text Area Cannot Be Empty...");
        } else {

            try {
                Class.forName("java.sql.DriverManager");
                Connection conn = (Connection) DriverManager.getConnection(
                        "jdbc:mysql://127.0.0.1/cafe_management_system",
                        userName,
                        password
                );
                Statement stmt = (Statement) conn.createStatement();
                String query = "INSERT INTO suppliers (sup_id, sup_name, sup_prod, phone_no, email_addr, address) "
                        + "VALUES (" + id + ", '" + supName + "', '" + supProd + "', '" + phoneNo + "', '" + emailAddr + "', '" + address + "');";
                if (stmt.executeUpdate(query) != 0) {
                    JOptionPane.showMessageDialog(this, "Supplier Record Saved Successfully...");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to Save Supplier Record...");
                }

                String queryGetID = "SELECT MAX(sup_id) FROM suppliers;";
                ResultSet resultSet = stmt.executeQuery(queryGetID);
                if (resultSet.next()) {
                    id = resultSet.getInt("MAX(sup_id)") + 1;
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to Update Supplier Id...");
                }
                jTextFieldSupplierId.setText(Integer.toString(id));

            } catch (ClassNotFoundException | SQLException exce) {
                JOptionPane.showMessageDialog(this, exce.getMessage());
            }
        }

    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        jTextFieldSupplierName.setText("");
        jTextFieldProduct.setText("");
        jTextFieldPhoneNumber.setText("");
        jTextFieldEmailAddress.setText("");
        jTextAreaAddress.setText("");

    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        dispose();

    }//GEN-LAST:event_jButtonCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertSupplierRecordJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertSupplierRecordJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertSupplierRecordJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertSupplierRecordJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertSupplierRecordJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabelEmailAddress;
    private javax.swing.JLabel jLabelEmailAddress1;
    private javax.swing.JLabel jLabelInsertSupplierRecord;
    private javax.swing.JLabel jLabelProduct;
    private javax.swing.JLabel jLabelProduct1;
    private javax.swing.JLabel jLabelSupplierId;
    private javax.swing.JLabel jLabelSupplierName;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelInsertCustomerRecord;
    private javax.swing.JScrollPane jScrollPaneAddress;
    private javax.swing.JTextArea jTextAreaAddress;
    private javax.swing.JTextField jTextFieldEmailAddress;
    private javax.swing.JTextField jTextFieldPhoneNumber;
    private javax.swing.JTextField jTextFieldProduct;
    private javax.swing.JTextField jTextFieldSupplierId;
    private javax.swing.JTextField jTextFieldSupplierName;
    // End of variables declaration//GEN-END:variables
}
