package cafemanagementsystem;

import java.sql.DriverManager;
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

public class InsertEmployeeRecordJFrame extends javax.swing.JFrame {

    /**
     * Creates new form InsertEmployeeRecordJFrame
     */
    int id;
    String userName = "root";
    String password = "password";

    private void addDays(int days) {
        for (int i = 1; i <= days; i++) {
            jComboBoxDay.addItem(Integer.toString(i));
        }
    }

    private void handleDateOfJoining() {
        int selectedMonth = jComboBoxMonth.getSelectedIndex() + 1;
        if (selectedMonth == 2) {
            jComboBoxDay.removeAllItems();
            addDays(28);
        } else if (selectedMonth < 8) {
            if (selectedMonth % 2 == 0) {
                jComboBoxDay.removeAllItems();
                addDays(30);
            } else {
                jComboBoxDay.removeAllItems();
                addDays(31);
            }
        } else {
            if (selectedMonth % 2 == 0) {
                jComboBoxDay.removeAllItems();
                addDays(31);
            } else {
                jComboBoxDay.removeAllItems();
                addDays(30);
            }
        }
    }

    public InsertEmployeeRecordJFrame() {
        initComponents();

        try {
            Class.forName("java.sql.DriverManager");
            Connection conn = (Connection) DriverManager.getConnection(
                    "jdbc:mysql://127.0.0.1/cafe_management_system",
                    userName,
                    password
            );
            Statement stmt = (Statement) conn.createStatement();
            String query = "SELECT MAX(emp_id) FROM employees;";
            ResultSet resultSet = stmt.executeQuery(query);
            if (resultSet.next()) {
                id = resultSet.getInt("MAX(emp_id)") + 1;
            } else {
                id = 1;
            }
            jTextFieldEmployeeId.setText(Integer.toString(id));

        } catch (ClassNotFoundException | SQLException exec) {
            JOptionPane.showMessageDialog(null, exec.getMessage());
        }

        handleDateOfJoining();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGender = new javax.swing.ButtonGroup();
        jPanelBackground = new javax.swing.JPanel();
        jButtonClear = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jPanelInsertCustomerRecord = new javax.swing.JPanel();
        jTextFieldEmployeeName = new javax.swing.JTextField();
        jLabelPhoneNumber = new javax.swing.JLabel();
        jLabelProductName = new javax.swing.JLabel();
        jLabelEmployeeId = new javax.swing.JLabel();
        jTextFieldEmployeeId = new javax.swing.JTextField();
        jLabelEmailAddress = new javax.swing.JLabel();
        jTextFieldPhoneNumber = new javax.swing.JTextField();
        jTextFieldEmailAddress = new javax.swing.JTextField();
        jLabelDateOfJoining = new javax.swing.JLabel();
        jLabelEmployeeTitle = new javax.swing.JLabel();
        jLabelEmployeeTitle1 = new javax.swing.JLabel();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jComboBoxMonth = new javax.swing.JComboBox<>();
        jLabelDash1 = new javax.swing.JLabel();
        jComboBoxDay = new javax.swing.JComboBox<>();
        jLabelDash2 = new javax.swing.JLabel();
        jTextFieldYear = new javax.swing.JTextField();
        jComboBoxEmployeeTitle = new javax.swing.JComboBox<>();
        jLabelResidence = new javax.swing.JLabel();
        jScrollPaneResidence = new javax.swing.JScrollPane();
        jTextAreaResidence = new javax.swing.JTextArea();
        jLabelInsertEmployeeRecord = new javax.swing.JLabel();
        jButtonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Insert Employee Record");
        setName("frameInsertEmployeeRecord"); // NOI18N
        setResizable(false);

        jPanelBackground.setBackground(new java.awt.Color(255, 248, 220));

        jButtonClear.setBackground(new java.awt.Color(255, 255, 255));
        jButtonClear.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jButtonClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-reset-24.png"))); // NOI18N
        jButtonClear.setMnemonic('C');
        jButtonClear.setText("Clear");
        jButtonClear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonSave.setBackground(new java.awt.Color(255, 255, 255));
        jButtonSave.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-save-24.png"))); // NOI18N
        jButtonSave.setMnemonic('S');
        jButtonSave.setText("Save");
        jButtonSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jPanelInsertCustomerRecord.setBackground(new java.awt.Color(255, 255, 255));
        jPanelInsertCustomerRecord.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldEmployeeName.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N

        jLabelPhoneNumber.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabelPhoneNumber.setText("Phone Number:");

        jLabelProductName.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabelProductName.setText("Employee Name:");

        jLabelEmployeeId.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabelEmployeeId.setText("Employee id:");

        jTextFieldEmployeeId.setEditable(false);
        jTextFieldEmployeeId.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jTextFieldEmployeeId.setFocusable(false);
        jTextFieldEmployeeId.setHighlighter(null);
        jTextFieldEmployeeId.setOpaque(false);

        jLabelEmailAddress.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabelEmailAddress.setText("Email Address:");

        jTextFieldPhoneNumber.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N

        jTextFieldEmailAddress.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N

        jLabelDateOfJoining.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabelDateOfJoining.setText("Date of Joining:");

        jLabelEmployeeTitle.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabelEmployeeTitle.setText("Employee Title:");

        jLabelEmployeeTitle1.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabelEmployeeTitle1.setText("Gender:");

        jRadioButtonMale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupGender.add(jRadioButtonMale);
        jRadioButtonMale.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jRadioButtonMale.setSelected(true);
        jRadioButtonMale.setText("Male");

        jRadioButtonFemale.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupGender.add(jRadioButtonFemale);
        jRadioButtonFemale.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jRadioButtonFemale.setText("Female");

        jComboBoxMonth.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jComboBoxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec" }));
        jComboBoxMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMonthActionPerformed(evt);
            }
        });

        jLabelDash1.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabelDash1.setText("-");

        jComboBoxDay.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N

        jLabelDash2.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabelDash2.setText("-");

        jTextFieldYear.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jTextFieldYear.setText("2022");

        jComboBoxEmployeeTitle.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jComboBoxEmployeeTitle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Cashier", "Chef", "Kitchen Supervisor", "Waiter", "Cleaner" }));

        jLabelResidence.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jLabelResidence.setText("Residence:");

        jTextAreaResidence.setColumns(20);
        jTextAreaResidence.setFont(new java.awt.Font("Trebuchet MS", 0, 13)); // NOI18N
        jTextAreaResidence.setRows(5);
        jScrollPaneResidence.setViewportView(jTextAreaResidence);

        javax.swing.GroupLayout jPanelInsertCustomerRecordLayout = new javax.swing.GroupLayout(jPanelInsertCustomerRecord);
        jPanelInsertCustomerRecord.setLayout(jPanelInsertCustomerRecordLayout);
        jPanelInsertCustomerRecordLayout.setHorizontalGroup(
            jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertCustomerRecordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInsertCustomerRecordLayout.createSequentialGroup()
                        .addComponent(jLabelEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                        .addComponent(jTextFieldEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelInsertCustomerRecordLayout.createSequentialGroup()
                        .addComponent(jLabelProductName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertCustomerRecordLayout.createSequentialGroup()
                        .addComponent(jLabelPhoneNumber)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertCustomerRecordLayout.createSequentialGroup()
                        .addComponent(jLabelDateOfJoining)
                        .addGap(68, 68, 68)
                        .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDash1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelDash2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldYear))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertCustomerRecordLayout.createSequentialGroup()
                        .addGroup(jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEmployeeTitle)
                            .addComponent(jLabelEmployeeTitle1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanelInsertCustomerRecordLayout.createSequentialGroup()
                                .addComponent(jRadioButtonMale)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonFemale))
                            .addComponent(jComboBoxEmployeeTitle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInsertCustomerRecordLayout.createSequentialGroup()
                        .addGroup(jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEmailAddress)
                            .addComponent(jLabelResidence))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldEmailAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(jScrollPaneResidence))))
                .addContainerGap())
        );

        jPanelInsertCustomerRecordLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabelDateOfJoining, jLabelEmailAddress, jLabelEmployeeId, jLabelEmployeeTitle, jLabelEmployeeTitle1, jLabelPhoneNumber, jLabelProductName});

        jPanelInsertCustomerRecordLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jComboBoxEmployeeTitle, jScrollPaneResidence, jTextFieldEmailAddress, jTextFieldEmployeeId, jTextFieldEmployeeName, jTextFieldPhoneNumber});

        jPanelInsertCustomerRecordLayout.setVerticalGroup(
            jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInsertCustomerRecordLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmployeeId)
                    .addComponent(jTextFieldEmployeeId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelProductName)
                    .addComponent(jTextFieldEmployeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhoneNumber)
                    .addComponent(jTextFieldPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmployeeTitle)
                    .addComponent(jComboBoxEmployeeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmployeeTitle1)
                    .addComponent(jRadioButtonMale)
                    .addComponent(jRadioButtonFemale))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDateOfJoining)
                    .addComponent(jComboBoxMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDash1)
                    .addComponent(jComboBoxDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDash2)
                    .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmailAddress)
                    .addComponent(jTextFieldEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInsertCustomerRecordLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInsertCustomerRecordLayout.createSequentialGroup()
                        .addComponent(jLabelResidence)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPaneResidence, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabelInsertEmployeeRecord.setFont(new java.awt.Font("Harrington", 1, 24)); // NOI18N
        jLabelInsertEmployeeRecord.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInsertEmployeeRecord.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-plus-+-48.png"))); // NOI18N
        jLabelInsertEmployeeRecord.setText("<html> \t<b style=\"color: #6f4e37;\"> \t\t&nbsp;Insert Employee Record \t</b> </html>");

        jButtonClose.setBackground(new java.awt.Color(255, 255, 255));
        jButtonClose.setFont(new java.awt.Font("Lucida Handwriting", 0, 14)); // NOI18N
        jButtonClose.setForeground(new java.awt.Color(204, 0, 0));
        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-macos-close-24.png"))); // NOI18N
        jButtonClose.setMnemonic('L');
        jButtonClose.setText("Close");
        jButtonClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBackgroundLayout = new javax.swing.GroupLayout(jPanelBackground);
        jPanelBackground.setLayout(jPanelBackgroundLayout);
        jPanelBackgroundLayout.setHorizontalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelInsertCustomerRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelBackgroundLayout.createSequentialGroup()
                        .addComponent(jButtonSave)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonClose))
                    .addComponent(jLabelInsertEmployeeRecord))
                .addContainerGap())
        );
        jPanelBackgroundLayout.setVerticalGroup(
            jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelInsertEmployeeRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelInsertCustomerRecord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonClose))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        String empName = jTextFieldEmployeeName.getText();
        String phoneNo = jTextFieldPhoneNumber.getText();
        String empTitle = (String) jComboBoxEmployeeTitle.getSelectedItem();
        String gender = "Male";
        if (jRadioButtonFemale.isSelected()) {
            gender = "Female";
        }

        int day = jComboBoxDay.getSelectedIndex() + 1;
        int month = jComboBoxMonth.getSelectedIndex() + 1;
        String year = jTextFieldYear.getText();
        String dateOfJoining;
        String emailAddr = jTextFieldEmailAddress.getText();
        String residence = jTextAreaResidence.getText();

        if (empName.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Employee Name Text Field Cannot Be Empty...");
        } else if (phoneNo.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Phone Number Text Field Cannot Be Empty...");
        } else if (year.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Date Of Joining (Year) Text Field Cannot Be Empty...");
        } else if (emailAddr.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Email Address Text Field Cannot Be Empty...");
        } else if (residence.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Residence Text Area Cannot Be Empty...");
        } else {
            dateOfJoining = year + "-" + month + "-" + day;

            try {
                Class.forName("java.sql.DriverManager");
                Connection conn = (Connection) DriverManager.getConnection(
                        "jdbc:mysql://127.0.0.1/cafe_management_system",
                        userName,
                        password
                );
                Statement stmt = (Statement) conn.createStatement();
                String query = "INSERT INTO employees "
                        + "(emp_id, emp_name, phone_no, emp_title, gender, emp_doj, email_addr, address) VALUES "
                        + "(" + id + ", '" + empName + "', '" + phoneNo + "', '" + empTitle + "', '" + gender + "', '" + dateOfJoining + "', '" + emailAddr + "', '" + residence + "');";
                if (stmt.executeUpdate(query) != 0) {
                    JOptionPane.showMessageDialog(this, "Employee Record Saved Successfully...");
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to Save Employee Record...");
                }

                String queryGetID = "SELECT MAX(emp_id) FROM employees;";
                ResultSet resultSet = stmt.executeQuery(queryGetID);
                if (resultSet.next()) {
                    id = resultSet.getInt("MAX(emp_id)") + 1;
                } else {
                    JOptionPane.showMessageDialog(this, "Failed to Update Employee ID...");
                }
                jTextFieldEmployeeId.setText(Integer.toString(id));

            } catch (ClassNotFoundException | SQLException exce) {
                JOptionPane.showMessageDialog(this, exce.getMessage());
            }

        }

    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        jTextFieldEmployeeName.setText("");
        jTextFieldPhoneNumber.setText("");
        jComboBoxEmployeeTitle.setSelectedIndex(0);
        jRadioButtonMale.setSelected(true);
        jComboBoxDay.setSelectedIndex(0);
        jComboBoxMonth.setSelectedIndex(0);
        jTextFieldYear.setText("2022");
        jTextFieldEmailAddress.setText("");
        jTextAreaResidence.setText("");

    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        dispose();

    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jComboBoxMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMonthActionPerformed
        handleDateOfJoining();

    }//GEN-LAST:event_jComboBoxMonthActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertEmployeeRecordJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertEmployeeRecordJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertEmployeeRecordJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertEmployeeRecordJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertEmployeeRecordJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupGender;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JComboBox<String> jComboBoxDay;
    private javax.swing.JComboBox<String> jComboBoxEmployeeTitle;
    private javax.swing.JComboBox<String> jComboBoxMonth;
    private javax.swing.JLabel jLabelDash1;
    private javax.swing.JLabel jLabelDash2;
    private javax.swing.JLabel jLabelDateOfJoining;
    private javax.swing.JLabel jLabelEmailAddress;
    private javax.swing.JLabel jLabelEmployeeId;
    private javax.swing.JLabel jLabelEmployeeTitle;
    private javax.swing.JLabel jLabelEmployeeTitle1;
    private javax.swing.JLabel jLabelInsertEmployeeRecord;
    private javax.swing.JLabel jLabelPhoneNumber;
    private javax.swing.JLabel jLabelProductName;
    private javax.swing.JLabel jLabelResidence;
    private javax.swing.JPanel jPanelBackground;
    private javax.swing.JPanel jPanelInsertCustomerRecord;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JScrollPane jScrollPaneResidence;
    private javax.swing.JTextArea jTextAreaResidence;
    private javax.swing.JTextField jTextFieldEmailAddress;
    private javax.swing.JTextField jTextFieldEmployeeId;
    private javax.swing.JTextField jTextFieldEmployeeName;
    private javax.swing.JTextField jTextFieldPhoneNumber;
    private javax.swing.JTextField jTextFieldYear;
    // End of variables declaration//GEN-END:variables
}
