package cafemanagementsystem;

public class MainMenuJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public MainMenuJFrame() {
        initComponents();

        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBackround = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanelMainMenu = new javax.swing.JPanel();
        jPanelCustomer = new javax.swing.JPanel();
        jLabelCustomerIcon = new javax.swing.JLabel();
        jLabelCustomer = new javax.swing.JLabel();
        jPanelEmployee = new javax.swing.JPanel();
        jLabelEmployeeIcon = new javax.swing.JLabel();
        jLabelEmployee = new javax.swing.JLabel();
        jPanelStock = new javax.swing.JPanel();
        jLabelStockIcon = new javax.swing.JLabel();
        jLabelStock = new javax.swing.JLabel();
        jPanelSupplier = new javax.swing.JPanel();
        jLabelSuplier = new javax.swing.JLabel();
        jLabelSupplierIcon = new javax.swing.JLabel();
        jPanelBill = new javax.swing.JPanel();
        jLabelBill = new javax.swing.JLabel();
        jLabelBillIcon = new javax.swing.JLabel();
        jPanelLogout = new javax.swing.JPanel();
        jLabelLogoutIcon = new javax.swing.JLabel();
        jLabelLogout = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cafe Management System - Main Menu");
        setName("frameMainMenu"); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jPanelBackround.setBackground(new java.awt.Color(255, 248, 220));

        jLabel1.setFont(new java.awt.Font("Harrington", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-cup-64.png"))); // NOI18N
        jLabel1.setText("<html>\n\t<b style=\"color: #6f4e37;\">\n\t\tCafe Management System - Main Menu\n\t</b>\n</html>");

        jPanelMainMenu.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMainMenu.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanelCustomer.setBackground(new java.awt.Color(255, 248, 220));
        jPanelCustomer.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelCustomer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelCustomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelCustomerMouseClicked(evt);
            }
        });

        jLabelCustomerIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCustomerIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-customer-100.png"))); // NOI18N

        jLabelCustomer.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        jLabelCustomer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCustomer.setText("Customer");

        javax.swing.GroupLayout jPanelCustomerLayout = new javax.swing.GroupLayout(jPanelCustomer);
        jPanelCustomer.setLayout(jPanelCustomerLayout);
        jPanelCustomerLayout.setHorizontalGroup(
            jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCustomerIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(jLabelCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCustomerLayout.setVerticalGroup(
            jPanelCustomerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCustomerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelCustomerIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCustomer)
                .addContainerGap())
        );

        jPanelEmployee.setBackground(new java.awt.Color(255, 248, 220));
        jPanelEmployee.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelEmployee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelEmployeeMouseClicked(evt);
            }
        });

        jLabelEmployeeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmployeeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-employee-100.png"))); // NOI18N

        jLabelEmployee.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        jLabelEmployee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEmployee.setText("Employee");

        javax.swing.GroupLayout jPanelEmployeeLayout = new javax.swing.GroupLayout(jPanelEmployee);
        jPanelEmployee.setLayout(jPanelEmployeeLayout);
        jPanelEmployeeLayout.setHorizontalGroup(
            jPanelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEmployeeIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(jLabelEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelEmployeeLayout.setVerticalGroup(
            jPanelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelEmployeeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelEmployeeIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelEmployee)
                .addContainerGap())
        );

        jPanelStock.setBackground(new java.awt.Color(255, 248, 220));
        jPanelStock.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelStock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelStock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelStockMouseClicked(evt);
            }
        });

        jLabelStockIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStockIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-notepad-100.png"))); // NOI18N

        jLabelStock.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        jLabelStock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStock.setText("Stock");

        javax.swing.GroupLayout jPanelStockLayout = new javax.swing.GroupLayout(jPanelStock);
        jPanelStock.setLayout(jPanelStockLayout);
        jPanelStockLayout.setHorizontalGroup(
            jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStockLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelStockIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelStockLayout.setVerticalGroup(
            jPanelStockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelStockLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelStockIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStock)
                .addContainerGap())
        );

        jPanelSupplier.setBackground(new java.awt.Color(255, 248, 220));
        jPanelSupplier.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSupplierMouseClicked(evt);
            }
        });

        jLabelSuplier.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        jLabelSuplier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSuplier.setText("Supplier");

        jLabelSupplierIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSupplierIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-supplier-100.png"))); // NOI18N

        javax.swing.GroupLayout jPanelSupplierLayout = new javax.swing.GroupLayout(jPanelSupplier);
        jPanelSupplier.setLayout(jPanelSupplierLayout);
        jPanelSupplierLayout.setHorizontalGroup(
            jPanelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSuplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelSupplierIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelSupplierLayout.setVerticalGroup(
            jPanelSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelSupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelSupplierIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSuplier)
                .addContainerGap())
        );

        jPanelBill.setBackground(new java.awt.Color(255, 248, 220));
        jPanelBill.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelBill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelBill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelBillMouseClicked(evt);
            }
        });

        jLabelBill.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        jLabelBill.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBill.setText("Bill");

        jLabelBillIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBillIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-bill-100.png"))); // NOI18N

        javax.swing.GroupLayout jPanelBillLayout = new javax.swing.GroupLayout(jPanelBill);
        jPanelBill.setLayout(jPanelBillLayout);
        jPanelBillLayout.setHorizontalGroup(
            jPanelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBillLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelBillIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelBillLayout.setVerticalGroup(
            jPanelBillLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBillLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelBillIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBill)
                .addContainerGap())
        );

        jPanelLogout.setBackground(new java.awt.Color(255, 248, 220));
        jPanelLogout.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelLogout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanelLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelLogoutMouseClicked(evt);
            }
        });

        jLabelLogoutIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogoutIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8-logout-100.png"))); // NOI18N

        jLabelLogout.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        jLabelLogout.setForeground(new java.awt.Color(204, 0, 0));
        jLabelLogout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogout.setText("Logout");

        javax.swing.GroupLayout jPanelLogoutLayout = new javax.swing.GroupLayout(jPanelLogout);
        jPanelLogout.setLayout(jPanelLogoutLayout);
        jPanelLogoutLayout.setHorizontalGroup(
            jPanelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLogoutIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(jLabelLogout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelLogoutLayout.setVerticalGroup(
            jPanelLogoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLogoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLogoutIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLogout)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelMainMenuLayout = new javax.swing.GroupLayout(jPanelMainMenu);
        jPanelMainMenu.setLayout(jPanelMainMenuLayout);
        jPanelMainMenuLayout.setHorizontalGroup(
            jPanelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainMenuLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelLogout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelMainMenuLayout.createSequentialGroup()
                        .addComponent(jPanelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jPanelEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jPanelStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jPanelSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jPanelBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMainMenuLayout.setVerticalGroup(
            jPanelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainMenuLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanelMainMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelStock, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBill, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70)
                .addComponent(jPanelLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout jPanelBackroundLayout = new javax.swing.GroupLayout(jPanelBackround);
        jPanelBackround.setLayout(jPanelBackroundLayout);
        jPanelBackroundLayout.setHorizontalGroup(
            jPanelBackroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackroundLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelBackroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1580, Short.MAX_VALUE)
                    .addComponent(jPanelMainMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelBackroundLayout.setVerticalGroup(
            jPanelBackroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBackroundLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jPanelMainMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(462, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBackround, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelCustomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelCustomerMouseClicked
        new ManageCustomerJFrame().setVisible(true);
        dispose();

    }//GEN-LAST:event_jPanelCustomerMouseClicked

    private void jPanelEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelEmployeeMouseClicked
        new ManageEmployeeJFrame().setVisible(true);
        dispose();

    }//GEN-LAST:event_jPanelEmployeeMouseClicked

    private void jPanelStockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelStockMouseClicked
        new ManageStockJFrame().setVisible(true);
        dispose();

    }//GEN-LAST:event_jPanelStockMouseClicked

    private void jPanelSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSupplierMouseClicked
        new ManageSupplierJFrame().setVisible(true);
        dispose();

    }//GEN-LAST:event_jPanelSupplierMouseClicked

    private void jPanelBillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelBillMouseClicked
        new GenerateBillJFrame().setVisible(true);

    }//GEN-LAST:event_jPanelBillMouseClicked

    private void jPanelLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelLogoutMouseClicked
        new LoginJFrame().setVisible(true);
        dispose();

    }//GEN-LAST:event_jPanelLogoutMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenuJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenuJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBill;
    private javax.swing.JLabel jLabelBillIcon;
    private javax.swing.JLabel jLabelCustomer;
    private javax.swing.JLabel jLabelCustomerIcon;
    private javax.swing.JLabel jLabelEmployee;
    private javax.swing.JLabel jLabelEmployeeIcon;
    private javax.swing.JLabel jLabelLogout;
    private javax.swing.JLabel jLabelLogoutIcon;
    private javax.swing.JLabel jLabelStock;
    private javax.swing.JLabel jLabelStockIcon;
    private javax.swing.JLabel jLabelSuplier;
    private javax.swing.JLabel jLabelSupplierIcon;
    private javax.swing.JPanel jPanelBackround;
    private javax.swing.JPanel jPanelBill;
    private javax.swing.JPanel jPanelCustomer;
    private javax.swing.JPanel jPanelEmployee;
    private javax.swing.JPanel jPanelLogout;
    private javax.swing.JPanel jPanelMainMenu;
    private javax.swing.JPanel jPanelStock;
    private javax.swing.JPanel jPanelSupplier;
    // End of variables declaration//GEN-END:variables
}
